env:
  global:
    - secure: DtHBOzqMh8DLwYNClXgqlvYZ8IcvULWUt2rpGSpj0DhdsQTGryP/8Q3oJXjugjXAV/sSilQrvaWmJteC+1OL1/qpeAF7Op3wadSYETCoKrjo2qKzvhBHyA09pg4Vf9kurOl294oHUBupL4Eqmuz4NgeJBNpXh7kp7dOkJ9xO9Ijcp2cRqa+3LcK/PJChkV7Wslx9RjmJPOsUIldALLsJUEW1NeDse+4A0cCOmntXOmBUgwZ75aF+DGhRb5wNfIBsLI1Jmx4tofWKda4G7mcRcaQwIx7CmUg8AGDnEYcsp3uMiyOKGHxb1KgRTNvLTnJxbh6eRKU4TkuHXKJWxjWgEnO6nAEPj38qmHpsz5p2cahsnVQ/5Pdtb7Y1YPfU1lEaiipMdk055/SBJlUZjR/+drH+TmUJ5KiqBLZRXYT3QbU6paI6qyslTxqHwGPHe+txE+0iWCddPySL0zkJYH/DtAifppzqdfDgP7mL1YFVMfXa8APySDeK8NINc/R+0pdz9gchaGGi4N327nurx7oi58poypEu5ylLH15f5kjkfDnEc/TnnQQiJHti+/OGFWZu90feVbTVZ3Yg2EWKPp7iGFCkrUfsfze3uk+HG90m7hSpy1v26yl0q1zHfM4SPubjFmwtrbxJs/hqWGhOLrbSzAiYXolJ4nMUoOP+hw8uMB4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_mvps.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
