env:
  global:
    - secure: dmgzIxxn4xvaHBgKO5RhcqJn3R/Xarn9BykaG1XN8SNwxJ7NdeZfpr5fvZ4OzEtfeL8fDNMuwyu9lhmf9l47ogOCkf2QM1PQXquy9/eCheRNS592QOVgMoUO1ECdGYeekfIAKnDUqZ2xEgnNR4B7SjmUvrLZ3/cQZ9d54tBeydr+moM94fMMOM6hYChofrYGmS6Z2NMjDOSr5McL8385sDP0eG6ee4VYg7SJ6KSbt52WqyTF3WUiFaKdpVrc1LBm9g5pv6sc36uPisSjB7STHMpZ+UqcyCQZDW5f1ifTkAIhuqIo0uu5dZx8RGA2HJseqbI2aF/BEm9Y9vVYuuMjXSp8kjWa9gAm1tAfFU9iHu8iwWfF7LFslxPFseLo3Cn2s7ag55UBQtg5nV635MvFTECzx7++z69xgE6yvdYfw/ZZDvDtoXwWfhsduc9JbK9Lf2ynfiSa45y0P4JupN2wcmzpYo/f1BYQ/RV9Qs2DNHMUvkmR8KvXyxnE8Wm+hZKPfnTIuDBuEPNkdYXlAjkJGORqj5+QIlpTTtzzHp7QXmW92flcQi/etesO46T1/W+wHdqV3N6k59hS+ZA1K1j5KncOMxOF8wmS+aLpjAuL9OpQd45L431iutOzJQA39Jbp9eXOp3qg3YShBjIwUd2pRyMRoVDXy8UW0QtZaawVzik=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_mvps.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
