dist: bionic
env:
    global:
    -   secure: AYwBmCODORyEZ3wB/V1C9FksnB9528fM0CQtNhCdSlK4eXQBcqf/UB+4QYfn2BFVPvjeH7rIgK3prbWsfJtJk0Bi4cl+Ohoo53vMUfkA0WnQzPR7KYJtvdYMcmW3Ji6jmdV1iRM1BXc0I9psAiMmauijyNjGQZIlp4ZhNF7xUFE017WkwJ0E/m9sZmb6JqV+n4SHJPsL1PUNiCvRhWi/9ZooAxtiTfUeLlpZU0h/oHY5DKFC+288Y3e5op2QHbx7t+F8DLiIuOx+nqm2EYQUs09VkCBizXu2J+rf62qZgEeLq8+dfBuBfc0lwDfJvIJgLoONi/xhmrdqBdwPxo6NX1hi9gM66yyy3ENLBgWmfr8DERWZbS8gVEf+IpHVE4VMrbsTADWyN8EynCe2OcCyF2yf8Us0hCE9uZIt1QX26a+KrMxU3klmyyVadj9WtPZfqabZCc/ck6JSk7OElGqFYpAg/TQheBbWqVMbf2bTzYjr2N5Am8KDFbP+aEjFNPSLzR0++qqOe2vM6/jgJ9DbVKBZlMCZHz6qaqwPCdU6ZK7eGVCchh8ooZ2GXYsRO5cu5DG+QRyA8iSdh/kfu8T4gjWeQ0IKlLDxToCVlLtNP2kUm0vA3toCB3hygLo4fZ2NMpQrL8G9SCR5D94K1LIKgYG1vUmPmVnfSbswIVFbejg=
    -   GIT_NAME: Dead-Hosts
    -   GIT_EMAIL: dead-hosts@outlook.com
    -   GIT_BRANCH: master
    -   PYTHON_VERSION: 3.7.5
install:
- export PATH="${HOME}/miniconda/bin:${PATH}"
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p ${HOME}/miniconda
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n launcher-environment python="${PYTHON_VERSION}"
- conda activate launcher-environment
- python -VV
- pip --version
- pip install --upgrade dead-hosts-launcher
- rm miniconda.sh
language: generic
notifications:
    email:
        on_failure: always
        on_success: change
        recipients:
        - dead-hosts@outlook.com
os:
- linux
script:
- dead_hosts_launcher --version
- dead_hosts_launcher
