env:
  global:
    - secure: pgxr2YTxyPtKaNPH9DyCG6vn8YKJ1nhYBIJygY/KsyiUmjYX5V9GGzAPQHkLVeMIaoR9Kjk7kT7VLWEaqsSoi/iuG1YlPiJCMCKvk/vVeV2AUIqJizRSbYNo7hBsSyLH+hg0YkZ1MFwIAaS1W+FGkhS5yiTaL05wiBPgWXfeX25FGgQplDvObbd8h7abOVILW8wr6HrO8ItAS3zZRLbq10EYKOMQLwnnvPikaU1A4Mjy7VOMYFUeI/S/ECJKvHXyiMSzWw0ZiihQPZFE+XG9A6y0PHuniR25bPDwWIK/1osaq9oi1AomeUWC6zTqaImwwCfA9UfCoCJ2SNEIMUNTSmouSjgVeGxeRrM0WknNbDFN6obxP/HVPCLabPnN9XCTarjCUWUdq9GAfmZsM0U6ff0gCNT++AfLPEfdYqasmRRIUFIw4ibTJf7sOX+B0YNxPwEq7ySHMMyyKtauiwNjKlB8hoFbQa8/gn1BgTuD6WUux5pehxv4mkje1PXnhUrKNuBt5fpvAEHcXFENW7wt+Z+3l+h/JE1+1xP4JsGCLKTyGskT3j9xdxHmYENh9fegVtprLo/lFgYAqauQETOzk2jeRnkTzWQnkEubWMIm8Gh0h7ZNhHgK3VEAqhI5YJ5Bm4XL1ccZB0+cC5uovf6P07Zm12syiuE/iaTmN+FLhaA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_mvps.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
