env:
  global:
    - secure: O9etGC+Yi9mxgKvQvg/xbGruNLdFOuGDViyPh30hb1NtvkpyOwF1Y8xe9WrcfGFq/Q4FcgvZaMJrdjOOVDr+uHJZ7a01zHkjN7ZDIgHU7lv0ooomZ2CeNLSCMVrbGMX9xuYxCb5NbM7v+IFUA3b0caVzI/adzM3o5QqispndDMV0xNxDJDMI8AW5xktdPGFjcASS97s4wXVk34R/DqsOIpfk2MssYblHD9nwm/YAPYxTEgSQ3lBo4K8kANVNWrFuZN4lWA2eufH2QR5XM7kaL2OWNeQkdmQwSNMFisVpEtJ0d6c3WNad6z0s0Kq3BVRXnKTQd75gLweXcuIkoDkUCGAEHGgIBgYZShVfQZ7iPtgqWJbK2wN/weulqxFEUcBPLhLQWurFgeS+qScpyau7ErR2CRlm4XKB6KILqw40muS3KdlR7TXZD7a6EiHxR3HSi9PihPPV5ykyB3p/f62ylCEjbxGjKP3SRNzWWX2/SgndAJ2kgtapoDMIzFIRKmUaM8ZGl5i6T8GqYDY4/lZwmd08w3xk/aH3eNY9Q3+UNcFOjx0nymczsWZHniyHk03SwdmvXtgq/+thAKAB0mLxz3bDgbvsMLLgH1xyjAPkNZEISnxJXS1pGEBMmfuy1HnffYqlrWo5dAepA0X1EN9hM3Qy4AD0ysiXxa1oUrZFoD0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_mvps.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
