env:
  global:
    - secure: PH7ys6i7YBaHuvKxJB5pPCs1XuS1CA/wNvgN/JgoE62RI/V13L1CT2gmJMQO3APmDqjdvzuG8LfesWHssvCqsE/M25l1LfbC6U/ZVfne5UT/bhGyBGXDSVDH2SoQ2wjXjwyvcFmzBZ+hqW5ZyQYfkY4IRkZ2au+eyGxb15WSUnzTGyPzSRWciRQsJUFojXmd4Qvgc4kBjphlx4R6YWihRGg75Pqw3CN0TzERs7ge9TuQ6PPvkZtrFhKNmjmqQInJcjh3VB7IK7I0i1/2MEj3D6wE4ogyT35x/pNgr2zvhtTDu00I6EyIvWCN3hm+rg0tEbBKd7F4rjpEF/vAEYBvS6Qr/XAyC3OE/uDKUADBcX1gZ34IoerHwsRrveS61CMbdQWq2lNIFuMKuVgz5ZoT4t7aZaO6hLs2J3RhPutPntiy9Dj+BOFgz06wYkUdYvjLx7Gipmfh1tqhAF39hJOm4lNn4FsL4I8P4eW31c+l9Vg+98SSHVOMbV5s102Sn++dO2EYJTcgH3DtMdU1qaK3uCmVLFlLgxIklaJpRmW7DCkgpDtspHnJYQuOXhXpsArJm7Dm4vgX84ewSGzkCEzmbG1HJMINo/Fqxn01CWJGS/yRZ4iGqRR1p60/02TAgu3fK86p75ofDwUHH6xvi/6U3WFWyzl5D9xxKIWvobZPf+k=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_mvps.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
