env:
  global:
    - secure: qHQM8/azsg2WU+UjS7ZTNhx7dvMDnnfdggX4rnfBIM5cbWA84JkdQjlk0VBXMMj7bEOYL/f5OUiw94Bl3hiJeS6/yz/Pl/0Ix/+MmtZs25gESJJbMiPKJMyxJYXvrEUG9uMAtPi8dgMyQ7+ANulI54V4LnigrREoG6j7ahvvGrI1Uy+ZVWIzf7JogFyPgFuYMx6WxABE4aj3sMWs/NQ4BslJ8rtKce053RGPUwtvt6Lgg+EyA7cOX4dvwbxWPdF/VFGjdSP20UH3ZyC/Ov9X9O7yUpIEI6YUr9mtwkdGXGqNv7g9Ay8q4PNI4PMAe5qL0iEypkSEziky592Ebw+CAekPJXvuwBEJ1bYbAPpE6DkI1eQAFqFyQgW9Unx+d6Zv8AMc6nIxACpeW1TQa+2Znge6wGYPtv6uJggDpuy73GCLTLp8E30toMijhaOZqek0g96UL/u9rpZJn1J3LWI6DWTpY5xSJxPnliDPd1in3HuruOIFXtmx2OcwyEeZmyg4R2H6GeD/FgYQONALKh6OzX4BMKwaEtT5JzqtxJ36Ox3Em4dlUZre16E2O7ghDY+01wBP+zKACswDPoZrG67UZZ8hfPgQxXXAjyNJLS4NdJkUewCuBFuzbRgusmo5r153k/ntxORDBUttGdMucGq16Kkg43o5b4pdWCnvE28oAzA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_mvps.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
