env:
  global:
    - secure: M2Pe6uHPcjld4ZJk8e8x/xZ4kgxrn38GdqogxShKcb6aV1czd+ydaaEl1t5uJCuh2lna3uKvFrDcRcwyXb0Ba1Dq9mDKyX9H5hu9ImBu1NGDYJJNFN6BouObUM9TGwFnMCfPjvvAm5abu/SumFT3eLoEcx11qdUW2RlAuBZ3Gwfpr7OPG+ytpx7SCJk3g+JXE7dZaXpkBrEFW0Tac9k+tUS1xFhmaKFn4mzzFIe6N02p+iHrt8jpRsZLN+XkbLVTx8RuPxMJdeDoSUCZ5Ilo4CJlM8wQkBN7edGUE6MDFSbQBMQk/o3XeK4/z6lKg/CvkoieW3w8zX+RpjE1BIH77iFsRoSlr46RrD4GMRALFqBauOBU1CuVAueRZk8wivvnn+BYpn1ZpSeyKPwC4BjaqeYsb1TgvmhZQU0E+gCV/XjKhRyssFKvsDY8DKQ2cWLsbuzkjaFr/Pcy9/gAj8uW4CLX2e8LCiPYmToI4mmLMil1fW6EewffUNjmobyH2eVrOmFXUTTbuAfvmpbTspVELqQ8c9VpCCTmTpB+PfTyWJI6art/ncQ768gQWloHgTWavnliRBPGAZHQjUNlRB5dxNpUU4GdIt2jQJMQepWlc6WHkqCHZLHYIF1LtA95ycD0erevh8sG3NVmQRlXaTs+uiag44PuVE7aHqQud7il02Q=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_mvps.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
