env:
  global:
    - secure: JkOk1RDhtbZZ6Mb9fIV+KqQnMKLAWwE4hRnxA5u34Kf3s4mOFn8f7UBUILYgUdGAyOYBdBfP+Cy21cQDLRNegC32+j49jDBYLAiaY8Z1ofPYkbvWCJ7BfLMEcpGhS1bEJQmrs9pPmyW+PVGXL7icAC7S3iTA9ecGqcH6jr5YHrUHnKKWMw5cD5fZx34BVJsdWFImBFddFDa0SDjfTd95A/g6bWAiV4mOjc84xtoQKkfv43c6TZFV+xQ27akfifSMV7Vp93e5P70UrpFesW1en7M/0MLNrUboGOjELL+SjnyDr0/pzaZC3dw8hQqMK62X3cvi3qA+TfVK1BlGWccrpAiHVrIoQIlI36I/NBWMq6iQYbQl+hSU8NrEVNFIVVXpuH1LuAiGOkptB+gpgqYJ7efMec/v+1jkHBoRqx9lPsL7ab0n7e1UuGxnu8Xf9oc5rYsu2P9BPKa2WKCKnD/NFtEyIIzjSjjvwL9IfA9LI8eJSdVH9cxV7madv7m680I+fbyZ/qt5sF7xd55PKWfJ3zQ3aHupKG2cMR2RxFRks5LYMSlLd17vO5YN5bvaHxjtEqZKD7QXgvHupKMUGAUBz9Jyp0790Cccqfp1u231TIi4slIwgB3qn29na4XEHrGeZGgrR7Malb1icw4UXwcLzad9A+cWPe5X4aTJ/usavnQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_mvps.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
